table CC_Register_SY19
	lineageTag: eca1f36b-4b35-47ef-96eb-0f0014500157

	column DocumentIDT#
		dataType: int64
		formatString: 0
		lineageTag: ab12c4ae-d681-4159-b304-77406f1d0344
		summarizeBy: sum
		sourceColumn: DocumentIDT#

		annotation SummarizationSetBy = Automatic

	column Students
		dataType: int64
		formatString: 0
		lineageTag: 4fccb29f-5827-46f2-a592-1bb71fcf1a9e
		summarizeBy: sum
		sourceColumn: Students

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		lineageTag: a8c8c245-7542-4592-a1d2-3bc069dc2b58
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: 592beaa4-c4cf-43fa-a12d-e0a03f446c92
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column 'School DBN'
		dataType: string
		lineageTag: a9c599f0-6c74-434f-ae87-48f5aac0f653
		summarizeBy: none
		sourceColumn: School DBN

		annotation SummarizationSetBy = Automatic

	column 'Reporting District'
		dataType: int64
		formatString: 0
		lineageTag: f20a7d3f-6755-467d-9bc7-891a0141ae3a
		summarizeBy: sum
		sourceColumn: Reporting District

		annotation SummarizationSetBy = Automatic

	column 'IEP Implemented Projected'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6cf96d09-2cf5-4182-8c1a-7f8f503a49f5
		summarizeBy: none
		sourceColumn: IEP Implemented Projected

		variation Variation
			isDefault
			relationship: b3c40e53-7e41-46a3-a294-ef2e269774c5
			defaultHierarchy: LocalDateTable_3fa8a3e2-b426-4346-865f-35f4a7a2f35c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Date IEP'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6c153598-c25b-491f-a980-6d378c2a31eb
		summarizeBy: none
		sourceColumn: Date IEP

		variation Variation
			isDefault
			relationship: aec3526f-f8d3-4c00-b9f5-ac61ba4f0f8c
			defaultHierarchy: LocalDateTable_20e772fa-574d-46da-a096-a27897fa0713.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Process Stage'
		dataType: string
		lineageTag: 6c6cec23-4afa-498e-9786-e7a01015474e
		summarizeBy: none
		sourceColumn: Process Stage

		annotation SummarizationSetBy = Automatic

	column 'Language of Instruction'
		dataType: string
		lineageTag: 0816111a-c06e-48f9-8eac-d526037ef887
		summarizeBy: none
		sourceColumn: Language of Instruction

		annotation SummarizationSetBy = Automatic

	column 'ELL Status'
		dataType: string
		lineageTag: b72e253c-82dd-492e-8ea4-b06000f05f1a
		summarizeBy: none
		sourceColumn: ELL Status

		annotation SummarizationSetBy = Automatic

	column Grade
		dataType: string
		lineageTag: aecae7ea-c032-463b-9d82-aaf14f4e5941
		summarizeBy: none
		sourceColumn: Grade

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: cef96a89-6b64-458b-a237-ae5469181d3d
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: d2a29dcd-0851-42f8-8099-8a5aaa093d01
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column 'Meal Status'
		dataType: string
		lineageTag: 2c3afe26-586d-46fc-a8fe-ee25016fed38
		summarizeBy: none
		sourceColumn: Meal Status

		annotation SummarizationSetBy = Automatic

	column 'Disability Classification'
		dataType: string
		lineageTag: c9b78596-a069-4924-94a8-74e562fe5fad
		summarizeBy: none
		sourceColumn: Disability Classification

		annotation SummarizationSetBy = Automatic

	column 'Home Language'
		dataType: string
		lineageTag: 45aabc46-650d-4678-9875-ead3a75a353a
		summarizeBy: none
		sourceColumn: Home Language

		annotation SummarizationSetBy = Automatic

	column 'Time Spent with Non-Disabled Peers'
		dataType: string
		lineageTag: cfb5b8ef-9da0-4d2c-a5c5-1efa54cbcc3f
		summarizeBy: none
		sourceColumn: Time Spent with Non-Disabled Peers

		annotation SummarizationSetBy = Automatic

	column ASOFDATE
		dataType: dateTime
		formatString: General Date
		lineageTag: c87ff4df-590c-43ac-902d-8a568b59e4b3
		summarizeBy: none
		sourceColumn: ASOFDATE

		variation Variation
			isDefault
			relationship: e74b74db-3b6b-42c6-ad5c-8ae5c305df07
			defaultHierarchy: LocalDateTable_dc523a51-a503-4843-a66a-72d1bd3ce135.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition CC_Register_SY19-ee1a2f1d-ed36-4b9b-bb29-fb9023bfdb6b = m
		mode: import
		source =
				let
				    Source = Sql.Databases("ES11VSESSQL06,31433"),
				    SEO_REPORTING = Source{[Name="SEO_REPORTING"]}[Data],
				    dbo_CC_Register_SY19 = SEO_REPORTING{[Schema="dbo",Item="CC_Register_SY19"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_CC_Register_SY19,{{"Reporting District", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Y","ELL",Replacer.ReplaceText,{"ELL Status"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","N","Not ELL",Replacer.ReplaceText,{"ELL Status"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

