table 'Demo Table'
	lineageTag: ec5a891d-5376-4d28-a06f-6ea1003bd2d8

	column Group
		dataType: string
		lineageTag: 1fe0f7af-ffb6-406f-8c10-6ad85aa4dc21
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column Subgroup
		dataType: string
		lineageTag: 65777f01-c48e-4105-a229-ada69ecf2e12
		summarizeBy: none
		sourceColumn: Subgroup
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Subgroup CAP'
		dataType: string
		lineageTag: 9d9940f5-df56-4c41-8bbd-9ad8f895a3b8
		summarizeBy: none
		sourceColumn: Subgroup CAP
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 447b61bd-8d43-4c66-a1d3-06d332e18309
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Demo Table-2e2756b4-972d-4d92-a8e6-903888ff13d8' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci3JyMtMziypVNJRcizOTMwD0cGejn5A2lApVgdVhVNOYnI2iPZxdPYG0kYYKjwyiwsSgTwQ0zM4wNHP0xnINMZQ51+SkVoEokM8XIOAtAmGivCMzJJUEO3hGeIKpE0hKnx8FIJLEktKi4FCQA6cNMeU9vMPUYBIIlgWSrGxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Group = _t, Subgroup = _t, #"Subgroup CAP" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Group", type text}, {"Subgroup", type text}, {"Subgroup CAP", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

