table ELIGIBILITY1
	lineageTag: 5e4ef37b-b9de-40a3-9a6d-a1dcb42d37b0

	measure '# of Kidsm' = format(sum(ELIGIBILITY1[# Of Kids]),"#,###")
		lineageTag: df5c2aca-f4e9-4996-b42b-af8b581eded8

	measure 'Margin of Errorm' = format(sum(ELIGIBILITY1[MarginOfError]),"#,###")
		lineageTag: be678ff7-b9a5-46f3-8628-eea041bca57f

	column Age
		dataType: string
		lineageTag: cee3a68d-664c-43d3-9b1d-54e392b566e8
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column GeographyId
		dataType: int64
		formatString: 0
		lineageTag: 324c7c46-60c5-4004-9c96-1de98721b5c7
		summarizeBy: none
		sourceColumn: GeographyId

		annotation SummarizationSetBy = Automatic

	column '# Of Kids'
		dataType: int64
		formatString: 0
		lineageTag: 9168e493-890e-4e51-9ea7-5b8d77ee4448
		summarizeBy: sum
		sourceColumn: # Of Kids

		annotation SummarizationSetBy = Automatic

	column MarginOfError
		dataType: int64
		formatString: 0
		lineageTag: 1b2e65fd-25f8-4f01-8937-b2b9f9e81836
		summarizeBy: sum
		sourceColumn: MarginOfError

		annotation SummarizationSetBy = Automatic

	partition ELIGIBILITY1-aaf5c9b1-e8d1-48c8-bb8d-1aac36bbc531 = m
		mode: import
		source =
				let
				    Source = Sql.Database("NDESQL22", "NDE_Datawarehouse", [Query="SELECT#(lf)#(tab)Age = a.[Name]#(lf)#(tab), [# Of Kids] = CAST(ef.PopulationCount as int)#(lf)#(tab),[MarginOfError] = CAST(ef.[PopulationMarginOfError] as int)#(lf)#(tab), ef.GeographyId#(lf)FROM [cat].[Fact_EligibilityFactors] ef#(lf)JOIN [cat].[Dim_AgeGroups] a ON#(lf)#(tab)ef.AgeGroupId = a.Id#(lf)JOIN [cat].[Dim_Geography] g ON#(lf)#(tab)ef.GeographyId = g.Id#(lf)--WHERE #(lf)#(tab)--g.IsCongressional = 0#(lf)#(tab)--AND g.IsCounty = 0#(lf)#(tab)--AND g.IsLegislative = 0#(lf)#(tab)--AND g.IsSchoolDistrict = 0"])
				in
				    Source

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/ELIGIBILITY1/Source.{ID,0}","Section1/ELIGIBILITY1/Source.{Age,1}","Section1/ELIGIBILITY1/Changed Type.{# of Kids,2}","Section1/ELIGIBILITY1/Source.{GeographyId,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/ELIGIBILITY1/Source.{ID,0}","Section1/ELIGIBILITY1/Source.{Age,1}","Section1/ELIGIBILITY1/Changed Type.{# of Kids,2}","Section1/ELIGIBILITY1/Source.{GeographyId,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

