table 'Access Selector'
	lineageTag: dcecfd9c-1585-4e37-9fd1-9e4f53104cf1

	measure 'Referral Rate City EOY' =
			
			SUM ( 'BI vw_ReferralsRateCitywide'[# Referrals] )
			    / SUM ( 'BI vw_ReferralsRateCitywide'[# Students] )
		lineageTag: 00e12b54-3ba1-4aaf-81d4-f9241fb94193

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Referral Rate City YTD' =
			
			SUM ( 'BI vw_ReferralsRateCitywide'[# Referrals YTD] )
			    / SUM ( 'BI vw_ReferralsRateCitywide'[# Students] )
		lineageTag: 62c6f66c-ceb7-47c5-830b-8b7f61b1924b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Referral Rate City' =
			
			VAR MySelection =
			    SELECTEDVALUE (
			        'Referral Rate Selector'[Referral Data Thru],
			        "End of School Year"
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        MySelection = "End of School Year",
			            IF (
			                MIN ( 'Referral School Year Toggle'[Referral School Year] ) = [CurrentSchoolYear],
			                BLANK (),
			                [Referral Rate City EOY]
			            ),
			        LEFT ( MySelection, 5 ) = "First", [Referral Rate City YTD],
			        [Referral Rate City EOY]
			    )
		lineageTag: 3dd7f423-b02c-4587-868d-d26437a222e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Referral Reeval Rate City EOY' =
			
			SUM ( 'BI vw_ReferralsRateCitywide'[# Reevals] )
			    / SUM ( 'BI vw_ReferralsRateCitywide'[# SWDs] )
		lineageTag: 0cab83d0-e6fd-4cad-9c05-633eabd3260e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Referral Reeval Rate City YTD' =
			
			SUM ( 'BI vw_ReferralsRateCitywide'[# Reevals YTD] )
			    / SUM ( 'BI vw_ReferralsRateCitywide'[# SWDs] )
		lineageTag: b76071f2-73bb-4d8f-afa9-64f22f0cece3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Referral Reeval Rate City' =
			
			VAR MySelection =
			    SELECTEDVALUE (
			        'Referral Rate Selector'[Referral Data Thru],
			        "End of School Year"
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        MySelection = "End of School Year",
			            IF (
			                MIN ( 'Referral School Year Toggle'[Referral School Year] ) = [CurrentSchoolYear],
			                BLANK (),
			                [Referral Reeval Rate City EOY]
			            ),
			        LEFT ( MySelection, 5 ) = "First", [Referral Reeval Rate City YTD],
			        [Referral Reeval Rate City EOY]
			    )
		lineageTag: e23119b5-d72a-43e7-b04f-46b7f224c490

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Compliance' =
			
			CALCULATE (
			    COUNT ( 'BI vw_SupsOfPsych'[Timeliness] ),
			    FILTER (
			        'BI vw_SupsOfPsych',
			        'BI vw_SupsOfPsych'[Timeliness] = "Less than 60 days"
			            || 'BI vw_SupsOfPsych'[Timeliness] = "Greater than 60 days"
			    )
			)
		formatString: #,0
		lineageTag: 22d7a784-1e7e-42f0-87ac-70d746a21d95

	measure 'Total Compliance Citywide' =
			
			CALCULATE (
			    COUNT ( 'BI vw_SupsOfPsychCitywide'[Timeliness] ),
			    FILTER (
			        'BI vw_SupsOfPsychCitywide',
			        'BI vw_SupsOfPsychCitywide'[Timeliness] = "Less than 60 days"
			            || 'BI vw_SupsOfPsychCitywide'[Timeliness] = "Greater than 60 days"
			    )
			)
		formatString: #,0
		lineageTag: 40d928df-95ab-4919-90f1-b8dca530e3c2

	measure 'Timeliness of Placement Over 10' =
			
			CALCULATE (
			    COUNT ( 'BI vw_SupsOfPsych'[TimelinessofPlacement] ),
			    FILTER (
			        'BI vw_SupsOfPsych',
			        'BI vw_SupsOfPsych'[TimelinessofPlacement] = "Placement After 10 Days"
			    )
			)
		formatString: 0
		lineageTag: 3de1f560-96a3-4e8c-b0f5-f22f2e8f9606

	measure 'Timeliness of Placement within 10' =
			
			CALCULATE (
			    COUNT ( 'BI vw_SupsOfPsych'[TimelinessofPlacement] ),
			    FILTER (
			        'BI vw_SupsOfPsych',
			        'BI vw_SupsOfPsych'[TimelinessofPlacement] = "Placement Within 10 Days"
			    )
			)
		formatString: 0
		lineageTag: 10cba82b-0690-4b1d-8e1d-845a85f24851

	measure 'Tri Student Count' =
			
			COUNT ( RPT_Triennials[StudentID] )
		formatString: 0
		lineageTag: a38a77fb-a695-4ce3-93eb-fdd116c80dcf

	measure 'Tri Follow up %' =
			
			CALCULATE ( SUM ( RPT_Triennials[IsFollowUpNeeded] ) / [Tri Student Count] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e7e03008-40c0-4606-a60c-16f46a20a464

	column 'Data Set'
		dataType: string
		lineageTag: 764a1b0c-290a-49b0-8307-ab5def5fc99f
		summarizeBy: none
		sourceColumn: Data Set

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 50e39ddd-e593-4968-9093-3a4e1b9925aa
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Short
		dataType: string
		lineageTag: 61241b50-4305-4642-87c4-d4025d233844
		summarizeBy: none
		sourceColumn: Short

		annotation SummarizationSetBy = Automatic

	partition 'Access Selector-0c09b98a-5903-4e2e-b685-86ad5d03d0e8' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WUlXIT1MILilNSc0rKVYozyzJUHDJLE5MyszJLMlMLVbSUTIEYlWF4HCXYqVYnWiloNS01KKixByFoMSSVKCUERCDmbGxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#"Data Set" = _t, Order = _t, Short = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Data Set", type text}, {"Order", Int64.Type}, {"Short", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_QueryRelationships = {"columnCount":3,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Access Selector/Changed Type.{Data Set,0}","Section1/Access Selector/Changed Type.{Order,1}","Section1/Access Selector/Changed Type.{Short,2}"],"ColumnCount":3,"KeyColumnNames":[],"ColumnIdentities":["Section1/Access Selector/Changed Type.{Data Set,0}","Section1/Access Selector/Changed Type.{Order,1}","Section1/Access Selector/Changed Type.{Short,2}"],"RelationshipInfo":[]}

