table 'New Referal Month Toggle'
	lineageTag: 527774cb-be0d-48de-bc79-8ad7af765fca

	column 'Referral Month Name'
		dataType: string
		lineageTag: 35f0bf17-9aea-4cae-b98e-f3e5792a7f99
		summarizeBy: none
		sourceColumn: Referral Month Name
		sortByColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 678ecdb3-4e87-4694-9ac1-ae163bc28487
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'New Referal Month Toggle-11561fb7-12cd-40b4-9784-4d2a13dc02e8' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8irNS1XSUTIyUYrVAfFyKoE8QyMwz7E0vbS4BMQ3BvODUwtKUnOTUotAQhAN/skl+VABU7CAX34ZXIkZWMQlNRkuYg6xJTGvNLEIbJEFWMAtNakIJmIJFvFNLErOALnLEOKSgqLMHBDXCCoLUmoEdFUsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Referral Month Name" = _t, Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Referral Month Name", type text}, {"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/New Referal Month Toggle/Changed Type.{Referral Month Name,0}","Section1/New Referal Month Toggle/Changed Type.{Column1,1}"],"ColumnCount":2,"KeyColumnNames":[],"ColumnIdentities":["Section1/New Referal Month Toggle/Changed Type.{Referral Month Name,0}","Section1/New Referal Month Toggle/Changed Type.{Column1,1}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

